# VacationPy
----

#### Note
* Keep an eye on your API usage. Use https://developers.google.com/maps/reporting/gmp-reporting as reference for how to monitor your usage and billing.

* Instructions have been included for each segment. You do not have to follow them exactly, but they are included to help you think through the steps.

In [1]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import gmaps
import os

# Import API key
from api_keys import g_key

### Store Part I results into DataFrame
* Load the csv exported in Part I to a DataFrame

In [2]:
output_weather_csv=pd.read_csv('weather_CSV/weather_data.csv') 
city_df=pd.DataFrame(output_weather_csv)
city_df

,Unnamed: 0,City,Lat,lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date
0,0,kodiak,57.7900,-152.4072,271.15,40,1,10.80,US,1615446322
1,1,povenets,62.8487,34.8262,256.24,88,0,1.89,RU,1615446323
2,2,puerto ayora,-0.7393,-90.3518,296.48,98,100,1.60,EC,1615446323
3,3,norman wells,65.2820,-126.8329,263.15,67,75,6.17,CA,1615446323
4,4,saldanha,-33.0117,17.9442,290.15,78,75,5.14,ZA,1615446323
...,...,...,...,...,...,...,...,...,...,...
554,554,betare oya,5.6000,14.0833,295.01,83,100,0.74,CM,1615446490
555,555,jieshi,22.8134,115.8257,298.71,67,4,6.14,CN,1615446490
556,556,la cruz,23.9167,-106.9000,288.15,95,94,1.49,MX,1615446491
557,557,rodrigues alves,-7.7380,-72.6509,293.18,97,97,0.30,BR,1615446491
558,558,alofi,-19.0595,-169.9187,298.15,73,68,1.03,NU,1615446491

### Humidity Heatmap
* Configure gmaps.
* Use the Lat and Lng as locations and Humidity as the weight.
* Add Heatmap layer to map.

In [30]:
#configure gmaps.
gmaps.configure(api_key=g_key)

#adding the location and longitud for the fig

locations= city_df[["Lat","lng"]]
#print(locations)
weight_humidity=city_df["Humidity"].astype(float)
#print(weight)

#inserting the map
fig=gmaps.figure()

#creating the heat leyer
heat_layer=gmaps.heatmap_layer(locations, weights=weight_humidity, dissipating=False, max_intensity=30,point_radius=5)

#adding the layer
fig.add_layer(heat_layer)

fig

Figure(layout=FigureLayout(height='420px'))

### Create new DataFrame fitting weather criteria
* Narrow down the cities to fit weather conditions.
* Drop any rows will null values.

In [33]:
#getting the cities with values lower 80 but higher that 70, wind speeds less that 10 mph and zero cloudiness
ideal_city_80_dg=city_df.loc[(city_df["Max Temp"] < 80)]
ideal_city_80_dg

Empty DataFrame
Columns: [Unnamed: 0, City, Lat, lng, Max Temp, Humidity, Cloudiness, Wind Speed, Country, Date]
Index: []

### Hotel Map
* Store into variable named `hotel_df`.
* Add a "Hotel Name" column to the DataFrame.
* Set parameters to search for hotels with 5000 meters.
* Hit the Google Places API for each city's coordinates.
* Store the first Hotel result into the DataFrame.
* Plot markers on top of the heatmap.

In [ ]:
# NOTE: Do not change any of the code in this cell

# Using the template add the hotel marks to the heatmap
info_box_template = """
<dl>
<dt>Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
</dl>
"""
# Store the DataFrame Row
# NOTE: be sure to update with your DataFrame name
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]
locations = hotel_df[["Lat", "Lng"]]

In [ ]:
# Add marker layer ontop of heat map


# Display figure